# Generated by Django 4.1 on 2023-10-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("layout", "0002_members_delete_users"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="members",
            options={"ordering": ["-date_joined"], "verbose_name_plural": "Members"},
        ),
        migrations.RemoveField(
            model_name="members",
            name="email",
        ),
        migrations.RemoveField(
            model_name="members",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="members",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="members",
            name="phone_number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
