# Generated by Django 4.1 on 2023-10-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("layout", "0004_alter_classes_class_date_alter_classes_slots_filled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classes",
            name="slots_filled",
            field=models.IntegerField(default=1),
        ),
    ]
