# Generated by Django 4.1 on 2023-10-25 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("layout", "0005_alter_classes_slots_filled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classes",
            name="slots_filled",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="bookings",
            unique_together={("user", "class_id")},
        ),
    ]
